pipeline:
  install:
    image: node:9.8.0
    commands:
      - node -v
      - npm -v
      - npm install express --save

  docker:
    image: plugins/docker
    registry: reg.k8s.adminscloud.com:5000
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    auto_tag: true
    repo: foo/dummyapp
    launch_debug: true
    debug: true
    when:
      branch: master
