pipeline:
  install:
    image: node:9.8.0-alpine
    commands:
      - node -v
      - npm -v
      - npm install express --save

  publish:
    image: plugins/docker
    registry: reg.k8s.adminscloud.com
    username: docker
    password: spass1
    dockerfile: Dockerfile
