pipeline:
  install:
    image: node:9.8.0
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  testing:
    image: node:9.8.0-alpine
    group: testing
    commands:
      - yarn run test

  lint:
    image: node:9.8.0-alpine
    group: testing
    commands:
      - yarn run lint
