pipeline:
  install:
    image: node:9.8.0-alpine
    commands:
      - node -v
      - npm -v
      - npm install express --save

  publish:
    image: plugins/docker
    registry: reg.k8s.adminscloud.com:5000
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    auto_tag: true
    repo: foo/dummyapp
    environment:
      DOCKER_LAUNCH_DEBUG: true
