pipeline:
  test:
    image: node:9.8.0-alpine
    group: testing
    commands:
      - node -v
      - npm -v
      - npm install express --save
      - npm install -g lint
      - node-lint app.js

  publish_docker:
    image: plugins/docker:1.12
    registry: reg.k8s.adminscloud.com:5000
    repo: reg.k8s.adminscloud.com:5000/foo/dummyapp
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    auto_tag: true
    launch_debug: true
    debug: true
    insecure: true
    when:
      branch: master
